import * as React from 'react';
import "./Blog.css"
import BlogCard from './BlogCard';
import Blog1 from "../assets/pix6.jpg"
import Blog2 from "../assets/pix2.jpeg"
import Blog3 from "../assets/blog3.jpeg"
import Blog4 from "../assets/logo.png"
import Blog5 from "../assets/blog5.jpeg"



const Blog = () => {



  return (
    <div className='Blog-Main-Container'>
        <h4 style={{textAlign:"center", margin:"15px 0", fontFamily: "cursive"}}>RECENT BLOG POSTS</h4>
        <div className='Blog-Main-Wrapper'>
            <BlogCard 
            title="NEW YEAR MESSAGE TO NIGERIANS"
           avatimage={Blog5}
            description="As we enter 2025, I wish everyone a happy and prosperous New Year. May you be rich in joy, success, and good health. As the new year dawns, it brings many hopes, aspirations, and prospects for better days. By the grace of God, 2025 will be..."
            blogdate="Jan. 1, 2025"
            fullheader="NEW YEAR MESSAGE TO NIGERIANS"
            para1="Fellow Nigerians, As we enter 2025, I wish everyone a happy and prosperous New Year. May you be rich in joy, success, and good health. As the new year dawns, it brings many hopes, aspirations, and prospects for better days. By the grace of God, 2025 will be a year of great promise in which we will fulfill our collective desires. Though 2024 posed numerous challenges to our citizens and households, I am confident that the New Year will bring brighter days. Economic indicators point to a positive and encouraging outlook for our nation. Fuel prices have gradually decreased, and we recorded foreign trade surpluses in three consecutive quarters. Foreign reserves have risen, and the Naira has strengthened against the US dollar, bringing greater stability."
            para2="The stock market's record growth has generated trillions of naira in wealth, and the surge in foreign investment reflects renewed confidence in our economy. Nevertheless, the cost of food and essential drugs remained a significant concern for many Nigerian households in 2024. In 2025, our government is committed to intensifying efforts to lower these costs by boosting food production and promoting local manufacturing of essential drugs and other medical supplies. We are resolute in our ambition to reduce inflation from its current high of 34.6% to 15%. With diligent work and God's help, we will achieve this goal and provide relief to all our people. In this new year, my administration will further consolidate and increase access to credit for individuals and critical sectors of the economy to boost national economic output."
            para3="To achieve this, the federal government will establish the National Credit Guarantee Company to expand risk-sharing instruments for financial institutions and enterprises. The Company—expected to start operations before the end of the second quarter—is a partnership of government institutions, such as the Bank of Industry, Nigerian Consumer Credit Corporation, the Nigerian Sovereign Investment Agency, and Ministry of Finance Incorporated, the private sector, and multilateral institutions. This initiative will strengthen the confidence of the financial system, expand credit access, and support under-served groups such as women and youth. It will drive growth, re-industrialisation, and better living standards for our people."
            para4="On a personal note, thank you for placing your confidence in me as your president. Your trust humbles me, and I promise to continue serving you diligently and wholeheartedly. We will continue to embark on necessary reforms to foster sustainable growth and prosperity for our nation. I seek your cooperation and collaboration at all times as we pursue our goal of a one trillion-dollar economy. Let us stay focused and united. We are on the right path to building a great Nigeria that will work for everyone. Let us not get distracted by a tiny segment of our population that still sees things through the prisms of politics, ethnicity, region, and religion."
            para5="CITIZENSHIP; To achieve our national goals and objectives, we must become better citizens and uncompromising in our devotion and allegiance to Nigeria. Citizens’ moral rectitude and faith in our country are fundamental to the success of the Renewed Hope Agenda. In 2025, we will commit to promoting adherence to ethical principles, shared values, and beliefs under the National Identity Project. I will unveil the National Values Charter, already approved by the Federal Executive Council, in the first quarter of 2025. I will launch an ambitious national orientation campaign that fosters patriotism and love for our country and inspires citizens to rally together. The Charter will promote mutual commitments between the government and citizens and foster trust and cooperation among our diverse population and between the government and the citizens. As far-reaching and foundational as our reforms are, they can produce the desired outcomes only through shared common values and identities and unconditional love for our country. The Youth Confab will begin in the first quarter of 2025, a testament to our commitment to youth inclusiveness and investment as nation-builders. The Ministry of Youth will soon announce the modalities for selecting the conference's representatives from our diverse, youthful population."
            para6="Dear Compatriots, I urge you to continue believing in yourselves and keeping faith in our blessed country. Let me use this New Year's message to urge our governors and local council chairpersons to work closely with the central government to seize emerging opportunities in agriculture, livestock, and tax reforms and move our nation forward. I commend governors who have embraced our Compressed Natural Gas initiative by launching CNG-propelled public transport. I also congratulate those who have adopted electric vehicles as part of our national energy mix and transition. The Federal Government will always offer necessary assistance to the states. To all citizens, your sacrifices have not been in vain over the past 19 months. I assure you they will not be in vain even in the months ahead. Together, let us stay the course of nation-building. The New Year will bring us closer to the bright future we all desire and the Nigeria of our dreams. God bless you all, and may God bless our beloved country, Nigeria. Happy New Year and a prosperous 2025 to you all!"
            blogclosing="Bola Ahmed Tinubu, President of the Federal Republic of Nigeria"
           />

            <BlogCard 
            title="Empowering the Future: Strategic Engagements for Nigerian Youth in 2025 - Dare Ojepe "
           avatimage={Blog4}
            description="Greetings to all esteemed youth and citizens of Nigeria, It is an exciting honor to address the exceptional opportunities that await our vibrant youth as we approach the pivotal year of 2025. The lessons and trials of the past have laid..."
            blogdate="Dec. 31, 2024"
            fullheader="Empowering the Future: Strategic Engagements for Nigerian Youth in 2025 - Dare Ojepe"
            para1="Greetings to all esteemed youth and citizens of Nigeria, It is an exciting honor to address the exceptional opportunities that await our vibrant youth as we approach the pivotal year of 2025. The lessons and trials of the past have laid the groundwork for innovation and growth. In this new era, Nigerian youth must actively participate in five strategic areas that will significantly influence not only their personal futures but also the destiny of our great nation."
            para2="1. Harnessing Technology and Digital Proficiency In our rapidly advancing world, technology sets the pace of development. It is imperative that our youth harness digital skills to unlock doors of opportunity. From mastering coding to excelling in digital marketing, the tech industry offers a wealth of prospects for those willing to take the plunge. Our administration is committed to supporting initiatives such as tech boot camps and online courses to enhance digital proficiency, enabling our youth to compete and excel on a global stage. By embracing cutting-edge tools, young Nigerians can drive meaningful innovations that address the unique challenges of our communities."
            para3="2. Active Civic Participation and Governance The active involvement of young Nigerians in civic affairs is not just encouraged; it is essential for strengthening our democracy. In 2025, we urge our youth to engage in governance through advocacy, voting, and grassroots community organization. By stepping into leadership roles, participating in local governance dialogues, and contributing to policy discussions, the youth can ensure their perspectives and needs are reflected in the legislative process. This engagement is crucial for shaping policies that are responsive to aspirations in areas like education and employment."
            para4="3. Cultivating Entrepreneurship and Innovation Nigeria's entrepreneurial spirit is one of its greatest assets. In 2025, we encourage our youth to pursue entrepreneurial ventures and innovative projects vigorously. The government is dedicated to facilitating access to incubators, mentorship, and funding to transform youthful ideas into sustainable businesses. We advocate for a focus on initiatives that foster social impact and address societal needs, thus driving job creation and economic growth within our communities."
            para5="4. Advocating Environmental Sustainability As custodians of Nigeria’s rich ecological heritage, our youth must lead the charge in advocating for environmental sustainability and proactive climate action. Engaging in initiatives like grassroots campaigns, community clean-ups, and adopting eco-friendly practices is essential. As we move into 2025, promoting awareness and spearheading activities to protect our biodiversity will safeguard our natural resources for future generations. The government's policies will continue to support and amplify these efforts, tapping the passion and creativity of our youth."
            para6="5. Building Networks and Strategic Collaborations In this era of globalization, collaboration is a cornerstone of success. We encourage Nigerian youth to build robust networks that reach beyond borders, encompassing diverse ethnic and cultural perspectives. Through exchange programs, active participation on social media, and collaborative ventures, young Nigerians can share insights, foster innovations, and strengthen bonds with their peers across Africa and the world. This interconnected network will serve as a formidable force for positive change and development. The horizon of 2025 holds immense promise for Nigeria’s dynamic youth. By leveraging technology, engaging in governance, nurturing entrepreneurship, championing sustainability, and fostering collaborative networks, our youth are poised to build a future brimming with possibilities. The journey may present challenges, yet with unity and unwavering commitment, Nigerian youth will not only empower themselves but will also elevate our nation to its rightful place on the world stage. Together, let us embrace this future with resolve and determination, continuing to lead as architects of change and progress."
            blogclosing="Dare Ojepe is the Senior Special Assistant to the President on Youth Engagement"
           />

            <BlogCard 
            title="Navigating Nigeria's Future: President Tinubu's Vision for Reform and Progress - Dare Ojepe"
           avatimage={Blog3}
            description="President Tinubu's recent statements at the inaugural media parley reflect a comprehensive and candid approach to various pressing issues in Nigeria. His..."
            blogdate="Dec. 27, 2024"
            fullheader="Navigating Nigeria's Future: President Tinubu's Vision for Reform and Progress - Dare Ojepe"
            para1="President Tinubu's recent statements at the inaugural media parley reflect a comprehensive and candid approach to various pressing issues in Nigeria. His comments touch on a mix of ongoing challenges, proposed reforms, and views on governance that demand a balanced examination."
            para2="Firstly, addressing the tragedy of stampedes in palliative distributions, President Tinubu points to organizational shortcomings rather than the charitable intentions themselves. While philanthropy has played a role in his political journey, the President underscores the importance of robust logistics to prevent such tragic events. This suggests a need for improved infrastructural planning and execution in welfare distribution programs."
            para3="On economic policies, President Tinubu emphasizes the strengthening of the Naira and denies spending in foreign currencies, underscoring a commitment to Nigeria's economic independence. His remarks on tax reforms and VAT indicate an enduring focus on fiscal policies designed to stabilize and grow the economy. However, he acknowledges the complexities surrounding VAT rates, inviting a broader debate that could engage stakeholders in crafting equitable tax strategies."
            para4="President Tinubu's stance on borrowing highlights a pragmatic view—it is not borrowing itself that's problematic, but rather ensuring that the borrowed funds are invested in developmental projects. This approach advocates for transparency and accountability in public finance management, which could bolster public trust and support for government spending initiatives.
                In agriculture, the President's plan to introduce 2,000 tractors signals a technological shift from traditional farming methods. This move is aimed at boosting productivity and modernizing the sector, which is vital for food security and economic diversification. Such innovation is crucial but must be supported by training and infrastructure to maximize its impact."
            para5="Security remains a pressing concern, and President Tinubu's assurance of improving conditions with a pledge to combat banditry and terrorism by 2025 reflects a commitment to national safety. Success in this realm not only enhances public confidence but also encourages economic and social development by enabling the free movement of people and goods.
                The President's comments on asset recovery resonate with ongoing anti-corruption campaigns. Reclaiming assets from corrupt former officials and civil servants demonstrates a zero-tolerance policy towards corruption, which is essential for governance credibility."
            para6="Lastly, the controversial removal of fuel subsidies is justified by President Tinubu as a necessary measure to prevent economic mismanagement and ensure domestic prosperity. His anecdote about a friend unable to afford fuel for luxury vehicles underscores the broader narrative of prudent resource management, even at the individual level.
                Overall, President Tinubu's statements reflect an ambitious and multifaceted policy agenda aimed at addressing Nigeria's economic, security, and institutional challenges. The success of these initiatives will depend on careful implementation, stakeholder engagement, and continued adherence to transparency and accountability. Critics may question the feasibility or execution of such a broad agenda, but it certainly charts a determined path forward for the nation."
            blogclosing="Dare Ojepe is the Senior Special Assistant to the President on Youth Engagement"
           />

            <BlogCard 
           title= "Embracing Tax Reform: A Call to Action for Nigeria's Youth - Dare Ojepe"
            avatimage={Blog2}
            description="At this significant crossroads, the future prosperity of Nigeria heavily relies on visionary reforms and active civic participation. One such critical..."
            blogdate="Dec. 23, 2024"
            fullheader="Embracing Tax Reform: A Call to Action for Nigeria's Youth - Dare Ojepe"
            para1="At this significant crossroads, the future prosperity of Nigeria heavily relies on visionary reforms and active civic participation. One such critical reform, currently pursued by President Bola Tinubu GCFR, involves the restructuring of our nation’s tax system—a move that promises to lay the foundation for sustainable economic growth and enhanced socio-economic equity.
                Let us begin with the essence of the reform. These changes are not just about numbers and policies; they represent a transformative vision for our country; one where resources are judiciously managed, and opportunities are equitably distributed among all Nigerians, especially the youth, who are the backbone of our nation."
            para2="Driving Economic Growth:
                The proposed tax reform is designed to foster an economic environment where businesses can thrive and innovation is encouraged. By broadening the tax base and ensuring efficiency in collection, the government aims to create a more stable economic foundation. This stability is crucial for attracting domestic and international investments which, in turn, translate to increased job opportunities, particularly for young Nigerians entering the workforce."
            para3="Enhancing Public Services:
                The link between tax reform and public service improvement cannot be overstated. With better compliance and fairer distribution, tax revenues can significantly boost funding for essential services such as education, healthcare, and infrastructure. Imagine schools with state-of-the-art facilities, hospitals with modern equipment, and roads that connect our nation seamlessly, all attainable with the right fiscal policies."
            para4="Empowering Youth and Entrepreneurs:
                One of the exciting aspects of these reforms is the focus on creating a supportive environment for youth entrepreneurship. The reforms include some tax exemptions for businesses with annual returns less than fifty million naira, which significantly benefits budding entrepreneurs. This measure encourages startups and small enterprises, enabling young Nigerians to transform their innovative ideas into flourishing businesses without the immediate pressure of financial burdens.
                Furthermore, the reform proposes some tax exemptions for employees whose annual income is less than ten million naira. This initiative directly impacts young professionals entering the workforce, allowing them to save more and invest in their future, thereby enhancing their economic stability."
            para5="Ensuring Transparency and Accountability:
                At the heart of any effective reform is transparency. The proposed changes include measures to enhance accountability in tax administration, ensuring that every naira collected is directed towards meaningful development projects. This approach aims to build public trust and foster a civic culture where contributing to national growth is seen as a collective responsibility."
            para6="A Call to Action:
                To the vibrant youth of our nation, your role in this transformation is indispensable. We urge you to engage in this dialogue, to understand the nuances of these policy shifts, and to advocate for transparent and equitable reforms. Your voices, your ideas, and your actions are essential in driving this change and securing a prosperous future for all.
                Let us unite with purpose and determination, embracing these reforms not as mere policy adjustments but as the stepping stones to a brighter Nigeria. Together, we can create an enduring legacy of prosperity and equity for generations to come."
           blogclosing=" Dare Ojepe is the Senior Special Assistant to the President on Youth Engagement"
           />

           <BlogCard 
            title="Empowering the Future: A Strategic Approach to Youth Engagement "
           avatimage={Blog1}
            description="In a notable development towards empowering Nigeria's youth, Dare Ojepe, the Senior Special Assistant to the President on Youth Engagement, met with..."
            blogdate="Dec. 18, 2024"
            fullheader="Empowering the Future: A Strategic Approach to Youth Engagement"
            para1="In a notable development towards empowering Nigeria's youth, Dare Ojepe, the Senior Special Assistant to the President on Youth Engagement, met with Mobolaji Ogunlende, the Commissioner for Youth and Social Development, Lagos. This significant meeting focused on crafting strategies to ensure active youth involvement in the nation’s developmental agenda."
            para2="The discussion centered around the renewed hope agenda, which aims to foster a sense of belonging and encourage youth participation across the country. Both leaders emphasized the importance of inclusivity, aiming to implement policies that ensure no young person is left behind."
            para3="Commissioner Ogunlende expressed optimism about the collaboration, highlighting the potential for their joint efforts to make a meaningful impact on youth empowerment in Nigeria. The productive exchange is expected to lead to initiatives that will drive substantial change and enhance the socio-economic landscape, ensuring that young Nigerians play a pivotal role in shaping the country's future."
           />      
        </div>
    </div>
  )
}

export default Blog